# MidupCore criado por Guilherme & ToddyDeveloper

motd: "                     &6&lMIDUP &f&lNETWORK &7(1.8.*) {newline}          &ewww.midup.com.br"
maintenance:
  enable: false
  motd: "                     &6&lMIDUP &f&lNETWORK &7(1.8.*) {newline}          &cServidor em desenvolvimento!"
  kick: "&cNosso servidor est√° em desenvolvimento no momento!"

  members:
    - "&emidup.com.br"
